author: 'Micah'
title: "www.micahlerner.com"
repository: "mlerner/mlerner.github.io"
plugins:
  - jekyll-feed
  - "jekyll-github-metadata"
feed: 
  collections:
    posts: 
      path: "/feed.xml"
collections:
  fragments:
    output: true
    permalink: /:collection/:title
  drafts:
    output: true