author: 'Micah'
title: "www.micahlerner.com"
plugins:
  - jekyll-feed
feed: 
  collections:
    posts: 
      path: "/feed.xml"
collections:
  fragments:
    output: true
    permalink: /:collection/:title
  drafts:
    output: true