author: 'Micah'
title: "www.micahlerner.com"
url: "http://www.micahlerner.com"
repository: "mlerner/mlerner.github.io"
plugins:
  - jekyll-feed
  - "jekyll-github-metadata"
feed: 
  collections:
    posts: 
      path: "/feed.xml"
collections:
  fragments:
    output: true
    permalink: /:collection/:title
  drafts:
    output: true
defaults:
  -
    scope:
      path: ""
    values:
      default_intro: "These paper reviews can [be delivered weekly to your inbox](https://newsletter.micahlerner.com/), or you can subscribe to the [Atom feed](https://www.micahlerner.com/feed.xml). As always, feel free to reach out on [Twitter](https://twitter.com/micahlerner) with feedback or suggestions!"
      include_default_intro: false